### ISSUE TITLE
ArcadeDb Studio - loading adjacent edges for more than one vertex, doesn't graphically connect the adjacent vertices

### ISSUE THREAD

**Issue by Jurgen-Aquilina** [ArcadeData/arcadedb#313]
## Expected behavior
Adjacent vertices should be graphically connected, identical to existing behaviour with the first usage.

## Actual behavior
First vertex expanded rendered correctly, adjacent vertices for subsequent ones are rendered without a connecting edge.

## Steps to reproduce
Load code
```
    for (i in 0..250000) {
        val tester = database.newVertex("Tester")
        tester.set("id", i.toString())
        database.async().createRecord(tester) {}

        val software = database.newVertex("Software")
        software.set("id", i.toString())

        database.async().createRecord(software) {}

        val client = database.newVertex("Client")
        client.set("id", i.toString())

        database.async().createRecord(client) {}
    }

    database.async().waitCompletion()

    for (i in 0..250000) {
        database.async().newEdgeByKeys(
            "Tester",
            arrayOf("id"),
            arrayOf(i),
            "Software",
            arrayOf("id"),
            arrayOf(i),
            false,
            "testerOf",
            true,
            true,
            null
        )

        database.async().newEdgeByKeys(
            "Software",
            arrayOf("id"),
            arrayOf(i),
            "Client",
            arrayOf("id"),
            arrayOf(i),
            false,
            "belongsTo",
            true,
            true,
            null
        )
    }

    database.async().waitCompletion()

    print("done")
```

GUI Steps:
* Select all Software vertices
* Click any Software vertex
* Click both under Actions -> Load adjacent outgoing, ingoing or both
* Click any Software vertex
* Click both under Actions -> Load adjacent outgoing, ingoing or both

**Comment by lvca** [comment]
This should be already fixed by the recent changes from the past week. Please @Jurgen-Aquilina let me know if you can check this with the latest snapshot. Thanks.

**Comment by Jurgen-Aquilina** [comment]
@lvca is the snapshot accessible through maven or do I need to add the JAR manually? If it is accessible through maven, can you link the repository please, as I cannot find it?

**Comment by lvca** [comment]
You should be able to find all the snapshots from this repository (put in your pom.xml before the tag <build>):

```
    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub ArcadeData Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/ArcadeData</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>
```

**Comment by arcade-player** [comment]
Errata

Snapshots are published on Sonatype OSS Maven repo:

https://s01.oss.sonatype.org/content/repositories/snapshots/

```xml
 <repositories>
        <repository>
            <id>github</id>
            <name>GitHub ArcadeData Apache Maven Packages</name>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>
```

**Comment by Jurgen-Aquilina** [comment]
@lvca I tested this again on 22.1.3-SNAPSHOT and the problem is still present

**Comment by lvca** [comment]
Added the snapshot repository in the ArcadeDB website under the "Getting Started with Java" section.

**Comment by lvca** [comment]
Tried with the Movie database and the load on request works. Check this video attached.

https://user-images.githubusercontent.com/312606/154758666-7918167d-dcc0-4d9e-a40e-bbf751291072.mov

**Comment by Jurgen-Aquilina** [comment]
@lvca I tested with the OpenBeer database and it works with that one, but not with my attempts. Seems like the issue is isolated to lightweight edges, as using regular edges removed the issue. This applies to issues #312 and #311 as well.

**Comment by lvca** [comment]
@Jurgen-Aquilina I found the cause, thanks for the report. I'll work on this soon.

**Comment by lvca** [comment]
Is this issue still relevant after I closed https://github.com/ArcadeData/arcadedb/issues/312 and https://github.com/ArcadeData/arcadedb/issues/311?

**Comment by lvca** [comment]
No response for a while, closing the issue. In case this issue is still relevant, please comment below to reopen it.
