### ISSUE TITLE
Cypher query returns Internal Error without any details of the actual error

### ISSUE THREAD

**Issue by emdax** [ArcadeData/arcadedb#696]
## Expected behavior
Return data like the same query cut and pasted from NEO4J

## Actual behavior
<img width="1440" alt="cypher_diff" src="https://user-images.githubusercontent.com/64988979/209029698-4350241c-aafc-4218-8ecb-5bac71c018be.png">

## Steps to reproduce
run this example cypher query:
```
merge ( x :Entry {u:"u1"} )-[ r:RUNS ]-( y :Port { u:"d2" } ) return x,r,y
```

**Comment by lvca** [comment]
Is the database public or can you share it? Do you see any stack trace in the server console?

**Comment by emdax** [comment]
On neo4j this query works in an empty blank database as this query automatically creates the missing nodes and relationships. Is different behavior expected with Arcade?

**Comment by artturimatias** [comment]
I can confirm this. Merge works if there exists nodes with same label but produces error if not. Only exception that if you do not set any properties, then you can merge node.

SIMPLE TEST CASE
This works with blank database:
`MERGE (n:NewItem) RETURN n`

But this fails with blank database:
`MERGE (n:NewNode {label:"some node"}) RETURN n`

error (truncated):
`<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.QueryParsingException: Error on executing Cypher query
	at com.arcadedb.gremlin.query.CypherQueryEngine.command(CypherQueryEngine.java:72)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1232)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:410)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:109)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:72)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:111)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: com.arcadedb.exception.SchemaException: Type with name 'NewItem' was not found
	at com.arcadedb.schema.EmbeddedSchema.getType(EmbeddedSchema.java:682)
	at org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeTraversalStrategy.apply(ArcadeTraversalStrategy.java:98)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.lambda$applyStrategies$2(DefaultTraversal.java:153)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalHelper.applyTraversalRecursively(TraversalHelper.java:468)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalHelper.applyTraversalRecursively(TraversalHelper.java:476)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:152)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:234)
	at org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeGremlin$1.hasNext(ArcadeGremlin.java:58)
	at com.arcadedb.query.sql.executor.IteratorResultSet.hasNext(IteratorResultSet.java:37)
	at org.apache.tinkerpop.gremlin.arcadedb.structure.ArcadeCypher.execute(ArcadeCypher.java:67)
	at com.arcadedb.gremlin.query.CypherQueryEngine.command(CypherQueryEngine.java:69)
	... 16 more
`

**Comment by artturimatias** [comment]
@lvca actually commented on this in discord:

> In ArcadeDB types must be created beforehand. They are part of the schema. You can just declare it with 
> `create vertex type Person` 
> sql statement or via API.

**Comment by lvca** [comment]
Correct. I can see the error is quite clear: "Caused by: com.arcadedb.exception.SchemaException: Type with name 'NewItem' was not found"

**Comment by lvca** [comment]
I see from the screenshot the error wasn't propagated correctly to Studio, so I'm still considering this a bug.

**Comment by lvca** [comment]
Fixed. Now the errors from the pluggable query engines are correctly propagated to the HTTP client, therefore Studio.

**Comment by emdax** [comment]
Just curious if there is an advantage to this constraint?

My impression is DBs like Arcade and Neo4j are fun because of quick and playful workflow -- the "schema" becomes a passive reflection or bi-product of creative flow. This is in contrast to more stubborn stiff databases which impose constraints and structure before the idea is born -- thus they drain precious bandwidth from the flow state.

I'm a huge fan of the "play with data" approach -- the way Cypher allows MERGE to auto-magically create all the missing LabelClasses behind the scenes -- while enabling the creator to stay in flow. 

Is there a downside to automatically creating missing Classes if MERGE is used, while saving the more formal error for CREATE ? 
(Extended from discord for the GitHub discussion)

**Comment by lvca** [comment]
Thanks for the input. Now the MERGE works, it's able to create new types if not existent.

**Comment by lvca** [comment]
Please let me know if the latest snapshot (`main` branch) works.

**Comment by emdax** [comment]
Pulled latest release. Even cleared and pruned sub layers. Still experiencing the same issue.

**Comment by emdax** [comment]
![illegalarg](https://user-images.githubusercontent.com/64988979/212988229-d5fa2f0c-9e4d-4ff2-94d9-3b439ba9c4ba.png)

**Comment by lvca** [comment]
It seems the latest docker image used Java>13 that is not compatible with Gremlin/Cypher: https://github.com/ArcadeData/arcadedb/issues/777
