### ISSUE TITLE
Postgres plugin not activating on windows start file

### ISSUE THREAD

**Issue by Jurgen-Aquilina** [ArcadeData/arcadedb#97]
## Expected behavior
Postgres Protocol plugin started displayed.

## Actual behavior
Starting ArcadeDB Server with plugins []... displayed

## Steps to reproduce
server.bat  -Darcadedb.server.plugins=Postgres

**Comment by lvca** [comment]
Fond the issue, the commands are passed after the class but they should be before the Java class.

```
java ... %CMD_LINE_ARGS% com.arcadedb.server.ArcadeDBServer
```

**Comment by lvca** [comment]
Ok, tested the unix/macosx/linux version and works. I don't have a Windows quickly to try.

Could you please get the latest distribution from git, build it (`mvn clean install -DskipTests`) and then:

```
server.bat -Darcadedb.server.plugins=Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
```

**Comment by Jurgen-Aquilina** [comment]
It gives the following error now 

> Ok, tested the unix/macosx/linux version and works. I don't have a Windows quickly to try.
> 
> Could you please get the latest distribution from git, build it (`mvn clean install -DskipTests`) and then:
> 
> ```
> server.bat -Darcadedb.server.plugins=Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
> ```

It gives the following error now:
```
Error: Could not find or load main class Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
Caused by: java.lang.ClassNotFoundException: Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
```

**Comment by Jurgen-Aquilina** [comment]
> I guess `:` cause troubles under Windows. Could you please try this:
> 
> ```
> server.bat -Darcadedb.server.plugins="Postgres:com.arcadedb.postgres.PostgresProtocolPlugin"
> ```
This displays "Starting ArcadeDB Server with plugins []... displayed"

**Comment by lvca** [comment]
I pushed a fix for that, please let me know if you can retry it after pulling from the latest version..

**Comment by Jurgen-Aquilina** [comment]
Apologies was occupied with other things. On the latest in main branch the provided command returns the ClassNotFoundException again unfortunately.

**Comment by lvca** [comment]
Hi @Jurgen-Aquilina any chance to retry this with the latest snapshot? Thanks in advance.

**Comment by Jurgen-Aquilina** [comment]
Problem persists with latest from main branch (SNAPSHOT 21.11.1)

**Comment by lvca** [comment]
Does anybody have a Windows machine that can help with this? Waiting for the final solution, this works for now: setting the plugin in `ARCADEDB_SETTING` environment variable and then run the server:

```
set ARCADEDB_SETTINGS=-Darcadedb.server.plugins="Postgres:com.arcadedb.postgres.PostgresProtocolPlugin"
bin\server.bat 
```

**Comment by shasaur** [comment]
For anyone trying this on Windows, note: the workaround does not work in the new Terminal, but does work in the old Command Prompt.

**Comment by LLuke** [comment]
There are bugs with the server.bat, for example, if I want to use a non-default databases location, it would throw errors like

```
.\arcadedb-23.10.1\bin\server.bat -Dserver.databaseDirectory=Z:\arcadedb\databases
...

ARCADEDB server script path = ...
ARCADEDB home directory     = ...
Error: Could not find or load main class Z:\arcadedb\databases
Caused by: java.lang.ClassNotFoundException: Z:\arcadedb\databases
```

Edit and add the options in the server.bat including postgres plugin settings will be fine, but such would fail with the command line.

**Comment by lvca** [comment]
I'm using server.sh and it correctly instances the Postgres plugin. By the way, how can we fix the server.bat? Adding quotes for paths?

**Comment by LLuke** [comment]
I just created a PR for you https://github.com/ArcadeData/arcadedb/pull/1333 and this also fixed https://github.com/ArcadeData/arcadedb/issues/173 under windows.
